Repository openshift/art-ci-toolkit, pull requests merged in 2019-10, with the labels that each got.

#1 Updated Dockerfile to use centos:8 image and added some missing packages
  Dockerfile
Labels: lgtm, size/S

#2 Use JsonOutput to generate JSON string
  vars/commentOnPullRequest.groovy
Labels: lgtm, size/XS

#3 Ignore file erratatool.yml when validating ocp-build-data
  vars/ocpBuildDataCISteps.groovy
Labels: size/XS
